//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from D:\Projects\.Net\StellarisTechTree\src\StellarisTechTree.WebApp\StellarisLocale.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

namespace StellarisTechTree.Infrastructure.Antlr.StellarisLocale;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="StellarisLocaleParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public interface IStellarisLocaleListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="StellarisLocaleParser.localeFile"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLocaleFile([NotNull] StellarisLocaleParser.LocaleFileContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="StellarisLocaleParser.localeFile"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLocaleFile([NotNull] StellarisLocaleParser.LocaleFileContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="StellarisLocaleParser.localeValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLocaleValue([NotNull] StellarisLocaleParser.LocaleValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="StellarisLocaleParser.localeValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLocaleValue([NotNull] StellarisLocaleParser.LocaleValueContext context);
}