//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from D:\Projects\.Net\StellarisTechTree\src\StellarisTechTree.WebApp\StellarisLocale.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System.CodeDom.Compiler;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;

namespace StellarisTechTree.Infrastructure.Antlr.StellarisLocale;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="StellarisLocaleParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[GeneratedCode("ANTLR", "4.7.2")]
[CLSCompliant(false)]
public interface IStellarisLocaleVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="StellarisLocaleParser.localeFile"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLocaleFile([NotNull] StellarisLocaleParser.LocaleFileContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StellarisLocaleParser.localeValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLocaleValue([NotNull] StellarisLocaleParser.LocaleValueContext context);
}