//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from D:\Projects\.Net\StellarisTechTree\src\StellarisTechTree.WebApp\StellarisLocale.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using System.CodeDom.Compiler;
using Antlr4.Runtime;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;

namespace StellarisTechTree.Infrastructure.Antlr.StellarisLocale;

/// <summary>
/// This class provides an empty implementation of <see cref="IStellarisLocaleListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[GeneratedCode("ANTLR", "4.7.2")]
[CLSCompliant(false)]
public partial class StellarisLocaleBaseListener : IStellarisLocaleListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="StellarisLocaleParser.localeFile"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLocaleFile([NotNull] StellarisLocaleParser.LocaleFileContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="StellarisLocaleParser.localeFile"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLocaleFile([NotNull] StellarisLocaleParser.LocaleFileContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="StellarisLocaleParser.localeValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLocaleValue([NotNull] StellarisLocaleParser.LocaleValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="StellarisLocaleParser.localeValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLocaleValue([NotNull] StellarisLocaleParser.LocaleValueContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}